stages:
  - qodana

qodana:
  stage: qodana
  only:
    - master
    - dev
    - merge_requests
  image:
    name: jetbrains/qodana-<linter>
    entrypoint: [""]
  variables:
    QODANA_REMOTE_URL: git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git
    QODANA_BRANCH: $CI_COMMIT_BRANCH
    QODANA_REPO_URL: $CI_PROJECT_URL
    QODANA_JOB_URL: $CI_JOB_URL
  script:
    - qodana --save-report --results-dir=$CI_PROJECT_DIR/qodana --report-dir=$CI_PROJECT_DIR/qodana/report
  artifacts:
    paths:
      - qodana/report/
    expose_as: 'Qodana report'